# -*- coding: utf-8 -*-
"""
100 个角色事件场景规则库

每个场景包含：
  id        : 唯一编号
  title     : 场景标题（≤10字）
  type      : personal_activity | social | physical_state | academic | emotional
  period    : morning(6-8) | forenoon(8-12) | noon(12-14) | afternoon(14-18) | evening(18-21) | night(21-24) | any
  location  : 宿舍 | 图书馆 | 实验室 | 食堂 | 操场 | 咖啡馆 | 教室 | 商业街 | 健身房 | 公园 | 校园 | 校医院 | 书店 | 学生活动中心 | 校外 | 任意
  conditions: 属性阈值条件列表
  changes   : 属性变化列表 [{attribute, delta}, ...]
"""

SCENE_RULES = [
    # ===== A. personal_activity — 个人日常活动（25个）=====
    {
        "id": 1,
        "title": "清晨起床洗漱",
        "type": "personal_activity",
        "period": "morning",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "energy", "delta": 10},
            {"attribute": "hygiene", "delta": 15},
            {"attribute": "mood", "delta": 2},
        ],
    },
    {
        "id": 2,
        "title": "晨跑3公里",
        "type": "personal_activity",
        "period": "morning",
        "location": "操场",
        "conditions": [{"attr": "health", "op": ">=", "val": 40}],
        "changes": [
            {"attribute": "energy", "delta": -5},
            {"attribute": "fitness", "delta": 2},
            {"attribute": "health", "delta": 1},
            {"attribute": "mood", "delta": 3},
        ],
    },
    {
        "id": 3,
        "title": "食堂吃早餐",
        "type": "personal_activity",
        "period": "morning",
        "location": "食堂",
        "conditions": [{"attr": "hunger", "op": ">=", "val": 50}],
        "changes": [
            {"attribute": "hunger", "delta": -12},
            {"attribute": "mood", "delta": 2},
            {"attribute": "energy", "delta": 2},
        ],
    },
    {
        "id": 4,
        "title": "图书馆自习3小时",
        "type": "personal_activity",
        "period": "forenoon|afternoon",
        "location": "图书馆",
        "conditions": [],
        "changes": [
            {"attribute": "learning", "delta": 2},
            {"attribute": "stress", "delta": 3},
            {"attribute": "energy", "delta": -6},
            {"attribute": "fulfillment", "delta": 4},
        ],
    },
    {
        "id": 5,
        "title": "午饭后小睡",
        "type": "personal_activity",
        "period": "noon",
        "location": "宿舍",
        "conditions": [{"attr": "energy", "op": "<=", "val": 40}],
        "changes": [
            {"attribute": "energy", "delta": 12},
            {"attribute": "mood", "delta": 2},
        ],
    },
    {
        "id": 6,
        "title": "在宿舍刷剧",
        "type": "personal_activity",
        "period": "evening|night",
        "location": "宿舍",
        "conditions": [{"attr": "boredom", "op": ">=", "val": 50}],
        "changes": [
            {"attribute": "boredom", "delta": -5},
            {"attribute": "mood", "delta": 3},
            {"attribute": "fulfillment", "delta": -3},
            {"attribute": "energy", "delta": 2},
        ],
    },
    {
        "id": 7,
        "title": "洗热水澡放松",
        "type": "personal_activity",
        "period": "evening|night",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "hygiene", "delta": 18},
            {"attribute": "stress", "delta": -4},
            {"attribute": "mood", "delta": 3},
            {"attribute": "energy", "delta": 2},
        ],
    },
    {
        "id": 8,
        "title": "深夜失眠",
        "type": "personal_activity",
        "period": "night",
        "location": "宿舍",
        "conditions": [
            {"attr": "stress", "op": ">=", "val": 60},
        ],
        "changes": [
            {"attribute": "energy", "delta": -6},
            {"attribute": "health", "delta": -2},
            {"attribute": "stress", "delta": 3},
            {"attribute": "boredom", "delta": 3},
        ],
    },
    {
        "id": 9,
        "title": "半夜起来喝水",
        "type": "personal_activity",
        "period": "night",
        "location": "宿舍",
        "conditions": [{"attr": "energy", "op": "<=", "val": 60}],
        "changes": [
            {"attribute": "energy", "delta": -1},
            {"attribute": "hunger", "delta": 2},
            {"attribute": "mood", "delta": 1},
        ],
    },
    {
        "id": 10,
        "title": "整理书桌和衣柜",
        "type": "personal_activity",
        "period": "any",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "fulfillment", "delta": 3},
            {"attribute": "boredom", "delta": -2},
            {"attribute": "confidence", "delta": 2},
        ],
    },
    {
        "id": 11,
        "title": "喝咖啡提神",
        "type": "personal_activity",
        "period": "forenoon|afternoon",
        "location": "咖啡馆",
        "conditions": [{"attr": "energy", "op": "<=", "val": 35}],
        "changes": [
            {"attribute": "energy", "delta": 4},
            {"attribute": "stress", "delta": 1},
            {"attribute": "mood", "delta": 1},
        ],
    },
    {
        "id": 12,
        "title": "写日记反思",
        "type": "personal_activity",
        "period": "night",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "mood", "delta": 2},
            {"attribute": "fulfillment", "delta": 3},
            {"attribute": "loneliness", "delta": -2},
        ],
    },
    {
        "id": 13,
        "title": "给盆栽浇水",
        "type": "personal_activity",
        "period": "any",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "mood", "delta": 2},
            {"attribute": "boredom", "delta": -1},
        ],
    },
    {
        "id": 14,
        "title": "做瑜伽拉伸",
        "type": "personal_activity",
        "period": "morning|evening",
        "location": "公园",
        "conditions": [],
        "changes": [
            {"attribute": "stress", "delta": -5},
            {"attribute": "fitness", "delta": 1},
            {"attribute": "health", "delta": 1},
            {"attribute": "mood", "delta": 3},
        ],
    },
    {
        "id": 15,
        "title": "吃零食解馋",
        "type": "personal_activity",
        "period": "afternoon|evening",
        "location": "宿舍",
        "conditions": [{"attr": "boredom", "op": ">=", "val": 40}],
        "changes": [
            {"attribute": "hunger", "delta": -5},
            {"attribute": "mood", "delta": 3},
            {"attribute": "joy", "delta": 2},
            {"attribute": "health", "delta": -1},
        ],
    },
    {
        "id": 16,
        "title": "熬夜赶论文",
        "type": "personal_activity",
        "period": "night",
        "location": "宿舍",
        "conditions": [{"attr": "writer_progress", "op": "<=", "val": 60}],
        "changes": [
            {"attribute": "energy", "delta": -12},
            {"attribute": "health", "delta": -3},
            {"attribute": "stress", "delta": 6},
            {"attribute": "writing", "delta": 2},
            {"attribute": "writer_progress", "delta": 2},
        ],
    },
    {
        "id": 17,
        "title": "清晨被噩梦惊醒",
        "type": "physical_state",
        "period": "morning",
        "location": "宿舍",
        "conditions": [{"attr": "mood", "op": "<=", "val": 30}],
        "changes": [
            {"attribute": "energy", "delta": -3},
            {"attribute": "mood", "delta": -4},
            {"attribute": "stress", "delta": 5},
            {"attribute": "loneliness", "delta": 3},
        ],
    },
    {
        "id": 18,
        "title": "一个人去食堂吃饭",
        "type": "personal_activity",
        "period": "noon|evening",
        "location": "食堂",
        "conditions": [{"attr": "loneliness", "op": ">=", "val": 50}],
        "changes": [
            {"attribute": "hunger", "delta": -12},
            {"attribute": "loneliness", "delta": 2},
            {"attribute": "mood", "delta": -1},
        ],
    },
    {
        "id": 19,
        "title": "大扫除整理房间",
        "type": "personal_activity",
        "period": "forenoon|afternoon",
        "location": "宿舍",
        "conditions": [{"attr": "hygiene", "op": "<=", "val": 30}],
        "changes": [
            {"attribute": "hygiene", "delta": 10},
            {"attribute": "fulfillment", "delta": 4},
            {"attribute": "energy", "delta": -4},
            {"attribute": "mood", "delta": 2},
        ],
    },
    {
        "id": 20,
        "title": "听音乐发呆",
        "type": "personal_activity",
        "period": "evening|night",
        "location": "宿舍",
        "conditions": [{"attr": "stress", "op": ">=", "val": 50}],
        "changes": [
            {"attribute": "stress", "delta": -5},
            {"attribute": "mood", "delta": 3},
            {"attribute": "creativity", "delta": 2},
        ],
    },
    {
        "id": 21,
        "title": "骑单车兜风",
        "type": "personal_activity",
        "period": "forenoon|afternoon",
        "location": "校园",
        "conditions": [],
        "changes": [
            {"attribute": "energy", "delta": -4},
            {"attribute": "fitness", "delta": 1},
            {"attribute": "stress", "delta": -3},
            {"attribute": "mood", "delta": 4},
            {"attribute": "joy", "delta": 3},
        ],
    },
    {
        "id": 22,
        "title": "复习考试内容",
        "type": "personal_activity",
        "period": "forenoon|afternoon|night",
        "location": "图书馆",
        "conditions": [],
        "changes": [
            {"attribute": "learning", "delta": 2},
            {"attribute": "stress", "delta": 4},
            {"attribute": "energy", "delta": -5},
            {"attribute": "fulfillment", "delta": 2},
        ],
    },
    {
        "id": 23,
        "title": "试穿新衣服",
        "type": "personal_activity",
        "period": "any",
        "location": "宿舍",
        "conditions": [{"attr": "confidence", "op": "<=", "val": 50}],
        "changes": [
            {"attribute": "confidence", "delta": 4},
            {"attribute": "mood", "delta": 3},
            {"attribute": "joy", "delta": 2},
        ],
    },
    {
        "id": 24,
        "title": "拍校园风景发朋友圈",
        "type": "personal_activity",
        "period": "forenoon|afternoon",
        "location": "校园",
        "conditions": [],
        "changes": [
            {"attribute": "mood", "delta": 3},
            {"attribute": "creativity", "delta": 1},
            {"attribute": "loneliness", "delta": -2},
        ],
    },
    {
        "id": 25,
        "title": "敷面膜护肤",
        "type": "personal_activity",
        "period": "night",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "hygiene", "delta": 5},
            {"attribute": "mood", "delta": 2},
            {"attribute": "confidence", "delta": 1},
        ],
    },

    # ===== B. social — 社交互动（25个）=====
    {
        "id": 26,
        "title": "和舍友去食堂吃饭",
        "type": "social",
        "period": "noon|evening",
        "location": "食堂",
        "conditions": [{"attr": "loneliness", "op": ">=", "val": 40}],
        "changes": [
            {"attribute": "hunger", "delta": -12},
            {"attribute": "loneliness", "delta": -5},
            {"attribute": "mood", "delta": 3},
            {"attribute": "social", "delta": 1},
        ],
    },
    {
        "id": 27,
        "title": "参加社团招新",
        "type": "social",
        "period": "noon|afternoon",
        "location": "学生活动中心",
        "conditions": [],
        "changes": [
            {"attribute": "social", "delta": 2},
            {"attribute": "loneliness", "delta": -4},
            {"attribute": "mood", "delta": 3},
            {"attribute": "confidence", "delta": 2},
        ],
    },
    {
        "id": 28,
        "title": "和闺蜜咖啡馆聊天",
        "type": "social",
        "period": "afternoon",
        "location": "咖啡馆",
        "conditions": [{"attr": "mood", "op": "<=", "val": 50}],
        "changes": [
            {"attribute": "mood", "delta": 5},
            {"attribute": "loneliness", "delta": -6},
            {"attribute": "joy", "delta": 4},
            {"attribute": "stress", "delta": -3},
        ],
    },
    {
        "id": 29,
        "title": "小组讨论课程项目",
        "type": "social",
        "period": "forenoon|afternoon",
        "location": "教室",
        "conditions": [],
        "changes": [
            {"attribute": "learning", "delta": 1},
            {"attribute": "social", "delta": 1},
            {"attribute": "stress", "delta": 2},
            {"attribute": "fulfillment", "delta": 2},
        ],
    },
    {
        "id": 30,
        "title": "班群里抢到红包",
        "type": "social",
        "period": "any",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "joy", "delta": 3},
            {"attribute": "mood", "delta": 2},
            {"attribute": "loneliness", "delta": -1},
        ],
    },
    {
        "id": 31,
        "title": "帮同学调代码bug",
        "type": "social",
        "period": "forenoon|afternoon",
        "location": "实验室",
        "conditions": [],
        "changes": [
            {"attribute": "coding", "delta": 2},
            {"attribute": "social", "delta": 1},
            {"attribute": "confidence", "delta": 3},
            {"attribute": "fulfillment", "delta": 4},
        ],
    },
    {
        "id": 32,
        "title": "被同学请喝奶茶",
        "type": "social",
        "period": "noon|afternoon",
        "location": "食堂",
        "conditions": [],
        "changes": [
            {"attribute": "mood", "delta": 3},
            {"attribute": "joy", "delta": 2},
            {"attribute": "loneliness", "delta": -3},
            {"attribute": "hunger", "delta": -2},
        ],
    },
    {
        "id": 33,
        "title": "和社团朋友聚餐",
        "type": "social",
        "period": "evening",
        "location": "商业街",
        "conditions": [{"attr": "loneliness", "op": ">=", "val": 50}],
        "changes": [
            {"attribute": "hunger", "delta": -13},
            {"attribute": "loneliness", "delta": -7},
            {"attribute": "mood", "delta": 4},
            {"attribute": "joy", "delta": 4},
            {"attribute": "social", "delta": 1},
        ],
    },
    {
        "id": 34,
        "title": "收到生日礼物",
        "type": "social",
        "period": "any",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "joy", "delta": 7},
            {"attribute": "mood", "delta": 5},
            {"attribute": "happiness", "delta": 4},
            {"attribute": "loneliness", "delta": -8},
        ],
    },
    {
        "id": 35,
        "title": "被朋友放鸽子",
        "type": "social",
        "period": "any",
        "location": "任意",
        "conditions": [],
        "changes": [
            {"attribute": "disappointment", "delta": 5},
            {"attribute": "anger", "delta": 3},
            {"attribute": "loneliness", "delta": 4},
            {"attribute": "mood", "delta": -5},
        ],
    },
    {
        "id": 36,
        "title": "图书馆偶遇同班好友",
        "type": "social",
        "period": "forenoon|afternoon",
        "location": "图书馆",
        "conditions": [{"attr": "loneliness", "op": ">=", "val": 40}],
        "changes": [
            {"attribute": "loneliness", "delta": -4},
            {"attribute": "mood", "delta": 3},
            {"attribute": "joy", "delta": 2},
        ],
    },
    {
        "id": 37,
        "title": "参加学院辩论赛",
        "type": "social",
        "period": "afternoon",
        "location": "教室",
        "conditions": [],
        "changes": [
            {"attribute": "confidence", "delta": 3},
            {"attribute": "social", "delta": 2},
            {"attribute": "stress", "delta": 4},
            {"attribute": "learning", "delta": 1},
        ],
    },
    {
        "id": 38,
        "title": "和朋友一起看电影",
        "type": "social",
        "period": "evening",
        "location": "校外",
        "conditions": [],
        "changes": [
            {"attribute": "mood", "delta": 5},
            {"attribute": "joy", "delta": 4},
            {"attribute": "loneliness", "delta": -6},
            {"attribute": "stress", "delta": -4},
        ],
    },
    {
        "id": 39,
        "title": "被同学背后议论",
        "type": "social",
        "period": "any",
        "location": "教室",
        "conditions": [],
        "changes": [
            {"attribute": "anger", "delta": 6},
            {"attribute": "disappointment", "delta": 4},
            {"attribute": "mood", "delta": -5},
            {"attribute": "confidence", "delta": -3},
            {"attribute": "loneliness", "delta": 3},
        ],
    },
    {
        "id": 40,
        "title": "主动约朋友散步",
        "type": "social",
        "period": "afternoon|evening",
        "location": "操场",
        "conditions": [{"attr": "loneliness", "op": ">=", "val": 50}],
        "changes": [
            {"attribute": "loneliness", "delta": -6},
            {"attribute": "mood", "delta": 4},
            {"attribute": "health", "delta": 1},
            {"attribute": "social", "delta": 1},
        ],
    },
    {
        "id": 41,
        "title": "参加志愿者活动",
        "type": "social",
        "period": "forenoon|afternoon",
        "location": "校外",
        "conditions": [],
        "changes": [
            {"attribute": "fulfillment", "delta": 6},
            {"attribute": "social", "delta": 2},
            {"attribute": "mood", "delta": 3},
            {"attribute": "happiness", "delta": 3},
        ],
    },
    {
        "id": 42,
        "title": "和舍友深夜卧谈",
        "type": "social",
        "period": "night",
        "location": "宿舍",
        "conditions": [{"attr": "loneliness", "op": ">=", "val": 40}],
        "changes": [
            {"attribute": "loneliness", "delta": -7},
            {"attribute": "mood", "delta": 3},
            {"attribute": "joy", "delta": 3},
            {"attribute": "energy", "delta": -3},
        ],
    },
    {
        "id": 43,
        "title": "看朋友圈秀恩爱感到孤独",
        "type": "emotional",
        "period": "any",
        "location": "宿舍",
        "conditions": [{"attr": "loneliness", "op": ">=", "val": 50}],
        "changes": [
            {"attribute": "loneliness", "delta": 5},
            {"attribute": "mood", "delta": -3},
            {"attribute": "disappointment", "delta": 2},
        ],
    },
    {
        "id": 44,
        "title": "学霸同学给{name}讲题",
        "type": "social",
        "period": "forenoon|afternoon",
        "location": "图书馆",
        "conditions": [{"attr": "learning", "op": "<=", "val": 50}],
        "changes": [
            {"attribute": "learning", "delta": 3},
            {"attribute": "mood", "delta": 3},
            {"attribute": "confidence", "delta": -2},
        ],
    },
    {
        "id": 45,
        "title": "和朋友打羽毛球",
        "type": "social",
        "period": "afternoon",
        "location": "操场",
        "conditions": [{"attr": "health", "op": ">=", "val": 40}],
        "changes": [
            {"attribute": "fitness", "delta": 2},
            {"attribute": "health", "delta": 1},
            {"attribute": "energy", "delta": -6},
            {"attribute": "mood", "delta": 4},
            {"attribute": "loneliness", "delta": -5},
        ],
    },
    {
        "id": 46,
        "title": "朋友失恋向{name}倾诉",
        "type": "social",
        "period": "afternoon|evening",
        "location": "咖啡馆",
        "conditions": [],
        "changes": [
            {"attribute": "loneliness", "delta": -3},
            {"attribute": "mood", "delta": -2},
            {"attribute": "fulfillment", "delta": 3},
            {"attribute": "social", "delta": 1},
        ],
    },
    {
        "id": 47,
        "title": "参加班级团建轰趴",
        "type": "social",
        "period": "evening",
        "location": "校外",
        "conditions": [],
        "changes": [
            {"attribute": "loneliness", "delta": -8},
            {"attribute": "joy", "delta": 6},
            {"attribute": "mood", "delta": 5},
            {"attribute": "social", "delta": 2},
            {"attribute": "energy", "delta": -8},
        ],
    },
    {
        "id": 48,
        "title": "被朋友借钱不还",
        "type": "social",
        "period": "any",
        "location": "任意",
        "conditions": [],
        "changes": [
            {"attribute": "anger", "delta": 4},
            {"attribute": "disappointment", "delta": 5},
            {"attribute": "mood", "delta": -4},
        ],
    },
    {
        "id": 49,
        "title": "和朋友们一起做饭",
        "type": "social",
        "period": "evening",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "mood", "delta": 4},
            {"attribute": "joy", "delta": 3},
            {"attribute": "loneliness", "delta": -5},
            {"attribute": "hunger", "delta": -8},
            {"attribute": "fulfillment", "delta": 3},
        ],
    },
    {
        "id": 50,
        "title": "被选为社团副部长",
        "type": "social",
        "period": "any",
        "location": "学生活动中心",
        "conditions": [],
        "changes": [
            {"attribute": "confidence", "delta": 6},
            {"attribute": "fulfillment", "delta": 5},
            {"attribute": "happiness", "delta": 4},
            {"attribute": "mood", "delta": 6},
            {"attribute": "stress", "delta": 3},
        ],
    },

    # ===== C. physical_state — 身体状态变化（10个）=====
    {
        "id": 51,
        "title": "淋雨感冒发烧",
        "type": "physical_state",
        "period": "any",
        "location": "校园",
        "conditions": [{"attr": "health", "op": "<=", "val": 50}],
        "changes": [
            {"attribute": "health", "delta": -10},
            {"attribute": "energy", "delta": -8},
            {"attribute": "mood", "delta": -5},
            {"attribute": "motivation", "delta": -3},
        ],
    },
    {
        "id": 52,
        "title": "食堂吃坏肚子",
        "type": "physical_state",
        "period": "any",
        "location": "食堂",
        "conditions": [],
        "changes": [
            {"attribute": "health", "delta": -8},
            {"attribute": "energy", "delta": -5},
            {"attribute": "hunger", "delta": 10},
            {"attribute": "mood", "delta": -4},
            {"attribute": "anger", "delta": 3},
        ],
    },
    {
        "id": 53,
        "title": "通宵后头痛",
        "type": "physical_state",
        "period": "any",
        "location": "宿舍",
        "conditions": [{"attr": "energy", "op": "<=", "val": 20}],
        "changes": [
            {"attribute": "health", "delta": -5},
            {"attribute": "energy", "delta": -3},
            {"attribute": "mood", "delta": -4},
            {"attribute": "motivation", "delta": -5},
        ],
    },
    {
        "id": 54,
        "title": "生理期身体不适",
        "type": "physical_state",
        "period": "any",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "energy", "delta": -5},
            {"attribute": "health", "delta": -2},
            {"attribute": "mood", "delta": -4},
            {"attribute": "motivation", "delta": -2},
            {"attribute": "anger", "delta": 2},
        ],
    },
    {
        "id": 55,
        "title": "运动受伤崴脚",
        "type": "physical_state",
        "period": "afternoon",
        "location": "操场",
        "conditions": [{"attr": "fitness", "op": ">=", "val": 40}],
        "changes": [
            {"attribute": "health", "delta": -8},
            {"attribute": "energy", "delta": -6},
            {"attribute": "mood", "delta": -5},
            {"attribute": "fitness", "delta": -2},
        ],
    },
    {
        "id": 56,
        "title": "做噩梦睡眠质量差",
        "type": "physical_state",
        "period": "night",
        "location": "宿舍",
        "conditions": [
            {"attr": "mood", "op": "<=", "val": 30},
            {"attr": "stress", "op": ">=", "val": 60},
        ],
        "changes": [
            {"attribute": "energy", "delta": -4},
            {"attribute": "health", "delta": -2},
            {"attribute": "mood", "delta": -3},
            {"attribute": "stress", "delta": 3},
        ],
    },
    {
        "id": 57,
        "title": "压力导致失眠",
        "type": "physical_state",
        "period": "night",
        "location": "宿舍",
        "conditions": [{"attr": "stress", "op": ">=", "val": 80}],
        "changes": [
            {"attribute": "health", "delta": -4},
            {"attribute": "energy", "delta": -8},
            {"attribute": "motivation", "delta": -3},
            {"attribute": "mood", "delta": -6},
        ],
    },
    {
        "id": 58,
        "title": "体检发现轻度贫血",
        "type": "physical_state",
        "period": "any",
        "location": "校医院",
        "conditions": [{"attr": "health", "op": "<=", "val": 40}],
        "changes": [
            {"attribute": "health", "delta": 5},
            {"attribute": "mood", "delta": -3},
            {"attribute": "motivation", "delta": -2},
        ],
    },
    {
        "id": 59,
        "title": "午睡睡过头错过上课",
        "type": "physical_state",
        "period": "noon",
        "location": "宿舍",
        "conditions": [{"attr": "energy", "op": "<=", "val": 30}],
        "changes": [
            {"attribute": "energy", "delta": 8},
            {"attribute": "stress", "delta": 5},
            {"attribute": "anger", "delta": 2},
            {"attribute": "confidence", "delta": -3},
        ],
    },
    {
        "id": 60,
        "title": "喝太多咖啡心悸",
        "type": "physical_state",
        "period": "forenoon|afternoon",
        "location": "咖啡馆",
        "conditions": [{"attr": "energy", "op": "<=", "val": 30}],
        "changes": [
            {"attribute": "health", "delta": -3},
            {"attribute": "energy", "delta": -2},
            {"attribute": "stress", "delta": 4},
            {"attribute": "mood", "delta": -3},
        ],
    },

    # ===== D. academic — 学业相关（20个）=====
    {
        "id": 61,
        "title": "完成期中考试",
        "type": "academic",
        "period": "forenoon|afternoon",
        "location": "教室",
        "conditions": [],
        "changes": [
            {"attribute": "stress", "delta": -5},
            {"attribute": "fulfillment", "delta": 3},
            {"attribute": "learning", "delta": 2},
            {"attribute": "energy", "delta": -5},
        ],
    },
    {
        "id": 62,
        "title": "论文初稿被导师表扬",
        "type": "academic",
        "period": "forenoon|afternoon",
        "location": "实验室",
        "conditions": [{"attr": "writer_progress", "op": ">=", "val": 30}],
        "changes": [
            {"attribute": "confidence", "delta": 5},
            {"attribute": "mood", "delta": 6},
            {"attribute": "motivation", "delta": 4},
            {"attribute": "writer_progress", "delta": 3},
            {"attribute": "player_trust", "delta": 2},
        ],
    },
    {
        "id": 63,
        "title": "论文被指出大问题需重写",
        "type": "academic",
        "period": "forenoon|afternoon",
        "location": "实验室",
        "conditions": [{"attr": "writer_progress", "op": ">=", "val": 20}],
        "changes": [
            {"attribute": "disappointment", "delta": 6},
            {"attribute": "stress", "delta": 8},
            {"attribute": "motivation", "delta": -4},
            {"attribute": "confidence", "delta": -5},
            {"attribute": "mood", "delta": -6},
        ],
    },
    {
        "id": 64,
        "title": "编程大作业完美运行",
        "type": "academic",
        "period": "forenoon|afternoon|night",
        "location": "实验室",
        "conditions": [{"attr": "coding", "op": ">=", "val": 50}],
        "changes": [
            {"attribute": "confidence", "delta": 6},
            {"attribute": "joy", "delta": 7},
            {"attribute": "fulfillment", "delta": 5},
            {"attribute": "coder_progress", "delta": 4},
            {"attribute": "coding", "delta": 2},
        ],
    },
    {
        "id": 65,
        "title": "期末考试周压力大",
        "type": "academic",
        "period": "forenoon|afternoon|night",
        "location": "图书馆",
        "conditions": [],
        "changes": [
            {"attribute": "stress", "delta": 8},
            {"attribute": "energy", "delta": -6},
            {"attribute": "health", "delta": -2},
            {"attribute": "loneliness", "delta": 3},
            {"attribute": "boredom", "delta": 2},
        ],
    },
    {
        "id": 66,
        "title": "组队参加编程竞赛",
        "type": "academic",
        "period": "forenoon|afternoon",
        "location": "实验室",
        "conditions": [],
        "changes": [
            {"attribute": "coding", "delta": 3},
            {"attribute": "social", "delta": 1},
            {"attribute": "stress", "delta": 5},
            {"attribute": "motivation", "delta": 5},
            {"attribute": "coder_progress", "delta": 3},
        ],
    },
    {
        "id": 67,
        "title": "对某专业课完全不感兴趣",
        "type": "academic",
        "period": "forenoon|afternoon",
        "location": "教室",
        "conditions": [],
        "changes": [
            {"attribute": "boredom", "delta": 4},
            {"attribute": "motivation", "delta": -3},
            {"attribute": "disappointment", "delta": 3},
            {"attribute": "fulfillment", "delta": -4},
        ],
    },
    {
        "id": 68,
        "title": "偶遇一本改变想法的书",
        "type": "academic",
        "period": "forenoon|afternoon",
        "location": "图书馆",
        "conditions": [],
        "changes": [
            {"attribute": "creativity", "delta": 6},
            {"attribute": "motivation", "delta": 5},
            {"attribute": "fulfillment", "delta": 4},
            {"attribute": "mood", "delta": 4},
        ],
    },
    {
        "id": 69,
        "title": "教授的课受启发",
        "type": "academic",
        "period": "forenoon|afternoon",
        "location": "教室",
        "conditions": [],
        "changes": [
            {"attribute": "motivation", "delta": 5},
            {"attribute": "learning", "delta": 2},
            {"attribute": "fulfillment", "delta": 4},
            {"attribute": "player_respect", "delta": 2},
        ],
    },
    {
        "id": 70,
        "title": "期末考试发挥失常",
        "type": "academic",
        "period": "forenoon|afternoon",
        "location": "教室",
        "conditions": [{"attr": "stress", "op": ">=", "val": 70}],
        "changes": [
            {"attribute": "disappointment", "delta": 7},
            {"attribute": "mood", "delta": -6},
            {"attribute": "confidence", "delta": -6},
            {"attribute": "motivation", "delta": -5},
        ],
    },
    {
        "id": 71,
        "title": "申请到国家级大创项目",
        "type": "academic",
        "period": "any",
        "location": "实验室",
        "conditions": [{"attr": "coding", "op": ">=", "val": 40}],
        "changes": [
            {"attribute": "confidence", "delta": 8},
            {"attribute": "motivation", "delta": 7},
            {"attribute": "fulfillment", "delta": 7},
            {"attribute": "coder_progress", "delta": 5},
            {"attribute": "stress", "delta": 4},
        ],
    },
    {
        "id": 72,
        "title": "每天写500字坚持一周",
        "type": "academic",
        "period": "any",
        "location": "宿舍",
        "conditions": [{"attr": "writer_progress", "op": ">=", "val": 20}],
        "changes": [
            {"attribute": "writing", "delta": 3},
            {"attribute": "writer_progress", "delta": 4},
            {"attribute": "confidence", "delta": 3},
            {"attribute": "fulfillment", "delta": 4},
        ],
    },
    {
        "id": 73,
        "title": "被同学抄袭被老师发现",
        "type": "academic",
        "period": "any",
        "location": "教室",
        "conditions": [],
        "changes": [
            {"attribute": "anger", "delta": 7},
            {"attribute": "disappointment", "delta": 5},
            {"attribute": "mood", "delta": -6},
        ],
    },
    {
        "id": 74,
        "title": "选修哲学课发现很有趣",
        "type": "academic",
        "period": "forenoon|afternoon",
        "location": "教室",
        "conditions": [],
        "changes": [
            {"attribute": "creativity", "delta": 5},
            {"attribute": "fulfillment", "delta": 4},
            {"attribute": "learning", "delta": 2},
            {"attribute": "mood", "delta": 3},
        ],
    },
    {
        "id": 75,
        "title": "获得二等奖学金",
        "type": "academic",
        "period": "any",
        "location": "教室",
        "conditions": [],
        "changes": [
            {"attribute": "confidence", "delta": 7},
            {"attribute": "happiness", "delta": 6},
            {"attribute": "joy", "delta": 8},
            {"attribute": "motivation", "delta": 5},
            {"attribute": "fulfillment", "delta": 6},
        ],
    },
    {
        "id": 76,
        "title": "和学霸在图书馆高效学习",
        "type": "academic",
        "period": "forenoon|afternoon",
        "location": "图书馆",
        "conditions": [
            {"attr": "loneliness", "op": ">=", "val": 40},
        ],
        "changes": [
            {"attribute": "learning", "delta": 3},
            {"attribute": "energy", "delta": -5},
            {"attribute": "fulfillment", "delta": 4},
            {"attribute": "motivation", "delta": 3},
            {"attribute": "loneliness", "delta": -3},
        ],
    },
    {
        "id": 77,
        "title": "对AI/NLP方向产生兴趣",
        "type": "academic",
        "period": "forenoon|afternoon",
        "location": "实验室",
        "conditions": [{"attr": "coding", "op": ">=", "val": 30}],
        "changes": [
            {"attribute": "motivation", "delta": 6},
            {"attribute": "fulfillment", "delta": 5},
            {"attribute": "creativity", "delta": 4},
            {"attribute": "coder_progress", "delta": 3},
        ],
    },
    {
        "id": 78,
        "title": "给学弟学妹做经验分享",
        "type": "academic",
        "period": "afternoon",
        "location": "教室",
        "conditions": [],
        "changes": [
            {"attribute": "confidence", "delta": 5},
            {"attribute": "fulfillment", "delta": 6},
            {"attribute": "social", "delta": 2},
            {"attribute": "mood", "delta": 4},
            {"attribute": "loneliness", "delta": -4},
        ],
    },
    {
        "id": 79,
        "title": "实习申请被拒",
        "type": "academic",
        "period": "any",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "disappointment", "delta": 8},
            {"attribute": "confidence", "delta": -6},
            {"attribute": "mood", "delta": -5},
            {"attribute": "motivation", "delta": -5},
        ],
    },
    {
        "id": 80,
        "title": "在学术会议做poster展示",
        "type": "academic",
        "period": "any",
        "location": "校外",
        "conditions": [],
        "changes": [
            {"attribute": "confidence", "delta": 7},
            {"attribute": "fulfillment", "delta": 8},
            {"attribute": "coder_progress", "delta": 5},
            {"attribute": "social", "delta": 2},
            {"attribute": "stress", "delta": -5},
        ],
    },

    # ===== E. emotional — 情绪事件（15个）=====
    {
        "id": 81,
        "title": "看到家人发来关心消息",
        "type": "emotional",
        "period": "any",
        "location": "宿舍",
        "conditions": [{"attr": "loneliness", "op": ">=", "val": 50}],
        "changes": [
            {"attribute": "loneliness", "delta": -6},
            {"attribute": "joy", "delta": 4},
            {"attribute": "mood", "delta": 4},
            {"attribute": "motivation", "delta": 3},
        ],
    },
    {
        "id": 82,
        "title": "想起高中好友很久未联系",
        "type": "emotional",
        "period": "night",
        "location": "宿舍",
        "conditions": [{"attr": "loneliness", "op": ">=", "val": 40}],
        "changes": [
            {"attribute": "loneliness", "delta": 5},
            {"attribute": "mood", "delta": -3},
        ],
    },
    {
        "id": 83,
        "title": "听歌突然想起前任",
        "type": "emotional",
        "period": "night",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "mood", "delta": -4},
            {"attribute": "loneliness", "delta": 4},
            {"attribute": "disappointment", "delta": 3},
        ],
    },
    {
        "id": 84,
        "title": "坚持完成一件事感到满足",
        "type": "emotional",
        "period": "any",
        "location": "任意",
        "conditions": [{"attr": "fulfillment", "op": ">=", "val": 60}],
        "changes": [
            {"attribute": "joy", "delta": 6},
            {"attribute": "happiness", "delta": 4},
            {"attribute": "motivation", "delta": 5},
            {"attribute": "confidence", "delta": 3},
        ],
    },
    {
        "id": 85,
        "title": "看到室友和男友视频感到羡慕",
        "type": "emotional",
        "period": "evening|night",
        "location": "宿舍",
        "conditions": [{"attr": "loneliness", "op": ">=", "val": 30}],
        "changes": [
            {"attribute": "loneliness", "delta": 4},
            {"attribute": "mood", "delta": -2},
            {"attribute": "disappointment", "delta": 2},
        ],
    },
    {
        "id": 86,
        "title": "整理旧照片发现成长",
        "type": "emotional",
        "period": "any",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "fulfillment", "delta": 5},
            {"attribute": "confidence", "delta": 3},
            {"attribute": "mood", "delta": 4},
            {"attribute": "motivation", "delta": 3},
        ],
    },
    {
        "id": 87,
        "title": "被陌生人夸穿搭好看",
        "type": "emotional",
        "period": "any",
        "location": "校园",
        "conditions": [],
        "changes": [
            {"attribute": "confidence", "delta": 4},
            {"attribute": "joy", "delta": 5},
            {"attribute": "mood", "delta": 4},
        ],
    },
    {
        "id": 88,
        "title": "梦见成为畅销书作家",
        "type": "emotional",
        "period": "night",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "motivation", "delta": 5},
            {"attribute": "creativity", "delta": 4},
            {"attribute": "mood", "delta": 3},
        ],
    },
    {
        "id": 89,
        "title": "看完励志电影充满干劲",
        "type": "emotional",
        "period": "evening",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "motivation", "delta": 7},
            {"attribute": "mood", "delta": 5},
            {"attribute": "fulfillment", "delta": 3},
            {"attribute": "stress", "delta": -3},
        ],
    },
    {
        "id": 90,
        "title": "体重增加2公斤心情低落",
        "type": "emotional",
        "period": "any",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "mood", "delta": -4},
            {"attribute": "confidence", "delta": -3},
            {"attribute": "motivation", "delta": -2},
        ],
    },
    {
        "id": 91,
        "title": "突然很想家但回不去",
        "type": "emotional",
        "period": "night",
        "location": "宿舍",
        "conditions": [{"attr": "loneliness", "op": ">=", "val": 50}],
        "changes": [
            {"attribute": "loneliness", "delta": 7},
            {"attribute": "mood", "delta": -5},
            {"attribute": "motivation", "delta": -3},
        ],
    },
    {
        "id": 92,
        "title": "逛书店发现期待的新书",
        "type": "emotional",
        "period": "forenoon|afternoon",
        "location": "书店",
        "conditions": [],
        "changes": [
            {"attribute": "joy", "delta": 6},
            {"attribute": "mood", "delta": 5},
            {"attribute": "creativity", "delta": 3},
            {"attribute": "fulfillment", "delta": 3},
        ],
    },
    {
        "id": 93,
        "title": "下雨天窝宿舍看书",
        "type": "emotional",
        "period": "any",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "mood", "delta": 4},
            {"attribute": "stress", "delta": -5},
            {"attribute": "joy", "delta": 3},
            {"attribute": "loneliness", "delta": -1},
            {"attribute": "creativity", "delta": 2},
        ],
    },
    {
        "id": 94,
        "title": "做好事被感谢感到温暖",
        "type": "emotional",
        "period": "any",
        "location": "任意",
        "conditions": [],
        "changes": [
            {"attribute": "fulfillment", "delta": 6},
            {"attribute": "joy", "delta": 5},
            {"attribute": "confidence", "delta": 3},
            {"attribute": "happiness", "delta": 3},
        ],
    },
    {
        "id": 95,
        "title": "设新年目标但担心完不成",
        "type": "emotional",
        "period": "any",
        "location": "宿舍",
        "conditions": [],
        "changes": [
            {"attribute": "motivation", "delta": 4},
            {"attribute": "stress", "delta": 3},
        ],
    },

    # ===== F. 与玩家关系事件（5个）=====
    {
        "id": 96,
        "title": "导师批改论文给详细建议",
        "type": "academic",
        "period": "forenoon|afternoon",
        "location": "实验室",
        "conditions": [{"attr": "writer_progress", "op": ">=", "val": 20}],
        "changes": [
            {"attribute": "player_trust", "delta": 3},
            {"attribute": "player_respect", "delta": 3},
            {"attribute": "motivation", "delta": 4},
            {"attribute": "confidence", "delta": 3},
        ],
    },
    {
        "id": 97,
        "title": "导师推荐参加学术会议",
        "type": "academic",
        "period": "any",
        "location": "实验室",
        "conditions": [{"attr": "player_trust", "op": ">=", "val": 40}],
        "changes": [
            {"attribute": "player_trust", "delta": 2},
            {"attribute": "player_intimacy", "delta": 2},
            {"attribute": "motivation", "delta": 6},
            {"attribute": "confidence", "delta": 5},
            {"attribute": "fulfillment", "delta": 5},
        ],
    },
    {
        "id": 98,
        "title": "导师误会自己很委屈",
        "type": "emotional",
        "period": "forenoon|afternoon",
        "location": "实验室",
        "conditions": [{"attr": "player_trust", "op": ">=", "val": 30}],
        "changes": [
            {"attribute": "disappointment", "delta": 5},
            {"attribute": "mood", "delta": -4},
            {"attribute": "anger", "delta": 3},
            {"attribute": "player_trust", "delta": -2},
        ],
    },
    {
        "id": 99,
        "title": "导师公开表扬{name}",
        "type": "academic",
        "period": "forenoon|afternoon",
        "location": "教室",
        "conditions": [],
        "changes": [
            {"attribute": "confidence", "delta": 6},
            {"attribute": "joy", "delta": 5},
            {"attribute": "player_affection", "delta": 3},
            {"attribute": "motivation", "delta": 4},
            {"attribute": "fulfillment", "delta": 4},
        ],
    },
    {
        "id": 100,
        "title": "和导师在咖啡馆聊未来",
        "type": "social",
        "period": "afternoon",
        "location": "咖啡馆",
        "conditions": [],
        "changes": [
            {"attribute": "player_intimacy", "delta": 5},
            {"attribute": "player_trust", "delta": 4},
            {"attribute": "motivation", "delta": 5},
            {"attribute": "confidence", "delta": 4},
            {"attribute": "mood", "delta": 5},
            {"attribute": "loneliness", "delta": -5},
        ],
    },
]
